### ISSUE TITLE
Error on 'charmap' codec can't encode character

### ISSUE THREAD

**Issue by arcontechnologies** [unclecode/crawl4ai#40] opened 2024-07-01 20:39 UTC
Hi,

Can someone explain why I'm experiencing this. I tried different urls and same outcome : 

```
🌟 Welcome to the Crawl4ai Quickstart Guide! Let's dive into some web crawling fun! 🌐
⛳️ First Step: Create an instance of WebCrawler and call the `warmup()` function.
If this is the first time you're running Crawl4ai, this might take a few seconds to load required model files.
[LOG] 🚀 Initializing LocalSeleniumCrawlerStrategy

DevTools listening on ws://127.0.0.1:61566/devtools/browser/ff15fd50-5eab-447a-97bb-1ca9d57126bb
[LOG] 🌤️  Warming up the WebCrawler
Error retrieving cached URL: no such column: links
[LOG] 🌞 WebCrawler is ready to crawl
🛠️  Basic Usage: Simply provide a URL and let Crawl4ai do the magic!
[LOG] 🕸️ Crawling https://www.morningstar.fr/fr using LocalSeleniumCrawlerStrategy...
Checking page load: 0
Checking page load: 1
Checking page load: 2
Checking page load: 3
Checking page load: 4
Checking page load: 5
[ERROR] 🚫 Failed to crawl https://www.morningstar.fr/fr, error: Failed to crawl https://www.morningstar.fr/fr: 'charmap' codec can't encode character '\uff1a' in position 237304: character maps to <undefined>
[LOG] 📦 Basic crawl result:
        Result:
        url: https://www.mornings...
        error_message: Failed to crawl http... 
```

Windows 11
Python 3.11

Any insight ?

**Comment by Nikky000** [comment] 2024-07-02 12:06
> Hi,
> 
> Can someone explain why I'm experiencing this. I tried different urls and same outcome :
> 
> ```
> 🌟 Welcome to the Crawl4ai Quickstart Guide! Let's dive into some web crawling fun! 🌐
> ⛳️ First Step: Create an instance of WebCrawler and call the `warmup()` function.
> If this is the first time you're running Crawl4ai, this might take a few seconds to load required model files.
> [LOG] 🚀 Initializing LocalSeleniumCrawlerStrategy
> 
> DevTools listening on ws://127.0.0.1:61566/devtools/browser/ff15fd50-5eab-447a-97bb-1ca9d57126bb
> [LOG] 🌤️  Warming up the WebCrawler
> Error retrieving cached URL: no such column: links
> [LOG] 🌞 WebCrawler is ready to crawl
> 🛠️  Basic Usage: Simply provide a URL and let Crawl4ai do the magic!
> [LOG] 🕸️ Crawling https://www.morningstar.fr/fr using LocalSeleniumCrawlerStrategy...
> Checking page load: 0
> Checking page load: 1
> Checking page load: 2
> Checking page load: 3
> Checking page load: 4
> Checking page load: 5
> [ERROR] 🚫 Failed to crawl https://www.morningstar.fr/fr, error: Failed to crawl https://www.morningstar.fr/fr: 'charmap' codec can't encode character '\uff1a' in position 237304: character maps to <undefined>
> [LOG] 📦 Basic crawl result:
>         Result:
>         url: https://www.mornings...
>         error_message: Failed to crawl http... 
> ```
> 
> Windows 11 Python 3.11
> 
> Any insight ?

got same error why scraping the url if you found the solution then please share your solution

**Comment by unclecode** [comment] 2024-07-03 06:02
@arcontechnologies  @Nikky000 This has been fixed and will be part of version 0.2.73 soon.

![image](https://github.com/unclecode/crawl4ai/assets/12494079/34f49973-ce68-4d73-9f35-8f9f8d597854)

**Comment by unclecode** [comment] 2024-07-03 06:06
@Ritha24 @Udara-Sampath The issue with llama3 is its inability to generate correct JSON, causing trouble in converting it to standard JSON. We are striving to introduce an additional layer to assist smaller or inadequately trained models producing JSON output. It's important to note that we can't guarantee complete accuracy, especially with smaller models. We are considering implementing a fallback model. Nevertheless, the upcoming helper layer is expected to address the majority of these issues, so please stay updated.

**Comment by xarchangel12** [comment] 2024-07-04 09:43
I am also getting the same error 

                                                
```
[LOG] 🚀 Initializing LocalSeleniumCrawlerStrategy

DevTools listening on ws://127.0.0.1:55270/devtools/browser/047fe112-fa77-4808-a19d-4e8330e43b76
[LOG] 🌤️  Warming up the WebCrawler
Error retrieving cached URL: no such column: links
[LOG] 🌞 WebCrawler is ready to crawl
Error retrieving cached URL: no such column: links
[ERROR] 🚫 Failed to crawl https://openai.com/api/pricing/, error: Failed to crawl https://openai.com/api/pricing/: 'charmap' codec can't encode character '\U0001f47b' in position 71832: character maps to <undefined>
None
```

**Comment by unclecode** [comment] 2024-07-05 05:55
@xarchangel12 Please remove the "~/.crawl4ai" folder, as you're using the old cache database version. My bad for not removing it during the new version install. I'm pushing 0.2.74, so you can reinstall it. In the meantime, remove the folder and then install the library again.

**Comment by arcontechnologies** [comment] 2024-07-05 08:16
@unclecode Hi, Still dealing with same error after upgrading to 0.2.73 and removing the .crawl4ai cache.

 Welcome to the Crawl4ai Quickstart Guide! Let's dive into some web crawling fun! 🌐
⛳️ First Step: Create an instance of WebCrawler and call the `warmup()` function.
If this is the first time you're running Crawl4ai, this might take a few seconds to load required model files.
[LOG] 🚀 Initializing LocalSeleniumCrawlerStrategy

DevTools listening on ws://127.0.0.1:65485/devtools/browser/4abcfd66-2a6b-4e93-aee4-3bf423bec128
[LOG] 🌤️  Warming up the WebCrawler
Error retrieving cached URL: no such column: links
[LOG] 🌞 WebCrawler is ready to crawl
🛠️  Basic Usage: Simply provide a URL and let Crawl4ai do the magic!
[LOG] 🕸️ Crawling https://openai.com/api/pricing/ using LocalSeleniumCrawlerStrategy...
[ERROR] 🚫 Failed to crawl https://openai.com/api/pricing/, error: Failed to crawl https://openai.com/api/pricing/: 'charmap' codec can't encode character '\U0001f47b' in position 74044: character maps to <undefined>
[LOG] 📦 Basic crawl result:
        Result:
        url: https://openai.com/a...
        error_message: Failed to crawl http...

**Comment by unclecode** [comment] 2024-07-05 09:16
@arcontechnologies Please clone the latest version from this link "https://github.com/unclecode/crawl4ai/tree/v0.2.74", ensure to remove the ".crawl4ai" folder. Afterwards, execute the provided code in a separate file, and instead of running the quickstart.py, run this code using your current version. Please let me know.

```python
import os
import sys
from pathlib import Path
import numpy as np
from crawl4ai.extraction_strategy import LLMExtractionStrategy
from crawl4ai.crawler_strategy import LocalSeleniumCrawlerStrategy
from crawl4ai.web_crawler import WebCrawler
from pydantic import BaseModel, Field

class OpenAIModelFee(BaseModel):
    model_name: str = Field(..., description="Name of the OpenAI model.")
    input_fee: str = Field(..., description="Fee for input token for the OpenAI model.")
    output_fee: str = Field(..., description="Fee for output token ßfor the OpenAI model.")

crawler = WebCrawler()
crawler.warmup()

url = r'https://openai.com/api/pricing/'

# Fetch a single page
result = crawler.run(
    url=url,
    word_count_threshold=1,
    extraction_strategy= LLMExtractionStrategy(
        provider= "openai/gpt-4o", api_token = os.getenv('OPENAI_API_KEY'), 
        schema=OpenAIModelFee.model_json_schema(),
        extraction_type="schema",
        instruction="""From the crawled content, extract all mentioned model names along with their fees for input and output tokens. 
        Do not miss any models in the entire content. One extracted model JSON format should look like this: 
        {"model_name": "GPT-4", "input_fee": "US$10.00 / 1M tokens", "output_fee": "US$30.00 / 1M tokens"}."""
    ),            
    bypass_cache=True,
)
```

**Comment by xarchangel12** [comment] 2024-07-06 08:08
> https://github.com/unclecode/crawl4ai/tree/v0.2.74

I deleted the "~/.crawl4ai" folder and I am still facing the same error 

```
[LOG] 🚀 Initializing LocalSeleniumCrawlerStrategy

DevTools listening on ws://127.0.0.1:51441/devtools/browser/2ced0dd3-a5e7-41a0-91c9-e58b1ea06d8a
[LOG] 🌤️  Warming up the WebCrawler
Error retrieving cached URL: no such column: links
[LOG] 🌞 WebCrawler is ready to crawl
Error retrieving cached URL: no such column: links
[ERROR] 🚫 Failed to crawl https://openai.com/api/pricing/, error: Failed to crawl https://openai.com/api/pricing/: 'charmap' codec can't encode character '\U0001f47b' in position 72375: character maps to <undefined>
None
```
and here is the test code I used like in the [video](https://www.youtube.com/watch?v=KAvuVUh0XU8) 

```from crawl4ai import WebCrawler

crawler = WebCrawler()

crawler.warmup()

result = crawler.run(url="https://openai.com/api/pricing/")
print(result.markdown)
```

**Comment by unclecode** [comment] 2024-07-08 08:22
@xarchangel12 Found it at last! I had been searching for this for a few days! Could you kindly clean up everything, then proceed with these steps and test your code again? The code below shows how I tested it on my Windows system. It is now functioning after resolving the problem.

```
mkdir crawl4ai-v74
git clone -b v0.2.74 https://github.com/unclecode/crawl4ai .\crawl4ai-v74\
py -3.11 -m venv myenv
pip install -e .
```

**Comment by unclecode** [comment] 2024-07-08 14:45
@xarchangel12 I have already pushed the latest version so you can clone the main branch and no need "v0.2.74", thx

**Comment by unclecode** [comment] 2024-07-08 23:50
@arcontechnologies Thx for your nice words and you are absolutely right. I will update it soon.

**Closed** 2024-07-09 05:02 UTC
Labels: bug, help wanted

**Comment by quangvinh2080** [comment] 2025-04-30 05:51
I'm still running into this error on Windows, the root cause is from `llmlite` package
Steps to reproduce:

```
python -m venv venv
.\venv\Scripts\activate
pip install crawl4ai
> python
> import litellm
> ....
> UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 1980: character maps to <undefined>
```

Looks like it’s a known issue: https://github.com/BerriAI/litellm/issues/10272
Switching to `llmlite==1.67.1` fixed it for me. Might help others running into the same thing!
