### ISSUE TITLE
'NoneType' object has no attribute 'get' 

### ISSUE THREAD

**Issue by bizrockman** [unclecode/crawl4ai#228] opened 2024-11-04 19:07 UTC
This is an exception coming from bs4 itself.

**utils.py**
```
imgs = body.find_all('img')
...
for img in imgs:        
  src = img.get('src', '')`
```

Sometimes resulting in
AttributeError: 'NoneType' object has no attribute 'get

Because the Tag does not have any attributes.
File "...\.venv\Lib\site-packages\bs4\element.py", line 1547, in get
    return self.attrs.get(key, default)

I have made a temp fix:

```
  for img in imgs:
      try:
          src = img.get('src', '')
          if base64_pattern.match(src):
              img['src'] = base64_pattern.sub('', src)
      except:
          pass
```

**Comment by aravindkarnam** [comment] 2024-11-05 05:31
@bizrockman Thanks for reporting this error. In what cases an img object is coming as 'NoneType'? Can you share a URL that causes this error to happen, so that I can reproduce this and root cause it.

**Comment by unclecode** [comment] 2024-11-06 13:48
@bizrockman I detected the issue and it has been resolved in the coming version, but I'd like to know, as @aravindkarnam  mentioned, the URL where this case occurred.

**Closed by unclecode** 2024-11-06 13:48 UTC
Labels: bug

**Comment by bizrockman** [comment] 2024-11-06 13:58
Sure it is on https://www.handgefertigtes.de

**Comment by unclecode** [comment] 2024-11-12 09:24
Thx for sharing the url
